export default function importClassNames(){//debe ser dinamico, no he encontrado como
    const classNames = [
        'borders1',
        'borders2',
        'color1',
        'color2',
        'color3',
        'color4',
        'color5',
        'colorTranparencia',
        'colorLetra1',
        'transparencia',
        'width100',
        'block',
        'maxWidth400',
        'borderNone',
        'verticalCenter',
        'horizontalCenter',
        'fixSpace',
        'halfLengthHorizontalAvailable',
        'quarterLengthOfAvailableVerticalSpace',
        'responsiveContainer',
        'halfHeightScreen',
        'equalSpace',
        'center',
        'rotate',
        'margin1',
        'marginTop1',
        'marginRight1',
        'marginLeft1',
        'marginBottom1',
        'margin2',
        'marginTop2',
        'marginRight2',
        'marginLeft2',
        'marginBottom2',
        'padding1',
        'buttonImage',
        'boxShadow1',
        'scroll',
        'cursor',
        'hoverBounce'
    ];

    return classNames
}